trigger:
- main

pool:
  name: Default

variables:
  imageName: java-game
  acrName: hackathonacr01

steps:

# Maven Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false

# SonarQube Scan
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'java-game'
    cliSources: '.'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

# Docker Build
- script: |
    docker build -t $(acrName).azurecr.io/$(imageName):$(Build.BuildId) .
  displayName: Docker Build

# Trivy Scan
- script: |
    trivy image $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: Trivy Scan

# Login to Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: 'service principal'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(acrName)

# Push to ACR
- script: |
    docker push $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
  displayName: Push Image

# Deploy to AKS
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'service principal'
    azureResourceGroup: 'hackathon-rg01'
    kubernetesCluster: 'hackathon-aks'
    command: apply
    useConfigurationFile: true
    configuration: 'deployment.yaml'
